//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinArk.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArkContext : DbContext
    {
        public ArkContext()
            : base("name=ArkContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<contact> contact { get; set; }
        public virtual DbSet<days> days { get; set; }
        public virtual DbSet<items> items { get; set; }
        public virtual DbSet<lecture_time> lecture_time { get; set; }
        public virtual DbSet<line> line { get; set; }
        public virtual DbSet<months> months { get; set; }
        public virtual DbSet<movies> movies { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<seats> seats { get; set; }
        public virtual DbSet<tickets> tickets { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
