//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinArk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class items
    {
        public int id { get; set; }
        public int product_id { get; set; }
        public int quantity { get; set; }
        public int price { get; set; }
        public int order_id { get; set; }
        public int customer_id { get; set; }
        public string movie { get; set; }
        public int room { get; set; }
        public int line { get; set; }
        public int seat { get; set; }
        public string month { get; set; }
        public string day { get; set; }
        public string lecture { get; set; }
    
        public virtual user user { get; set; }
        public virtual line line1 { get; set; }
        public virtual seats seats { get; set; }
    }
}
